### ISSUE TITLE
Calling "maybeRemoveImport(...)" does not remove import

### ISSUE THREAD

**Issue by michael-schnell** [openrewrite/rewrite-migrate-java#262]
## What version of OpenRewrite are you using?
2.0.7

## How are you running OpenRewrite?
Unit Test

## What is the smallest, simplest way to reproduce the problem?
Clone the project https://github.com/michael-schnell/openrewrite-issue/ and run the unit tests.

## What did you expect to see?
There should be no test failure.

## What did you see instead?
The Joda import is still there and makes the unit tests fail:
`import org.joda.time.format.DateTimeFormatterBuilder;`

## Example
![openrewrite-issue](https://github.com/openrewrite/rewrite-migrate-java/assets/1856319/2c444e5a-abe3-42c0-813b-8d71b67622cc)

**Comment by MBoegers** [comment]
Hi,
In your example the DateTimeFormatterBuilder is still imported because it’s still used in line 41 as return type.

Best Merlin
________________________________
Von: Michael Schnell ***@***.***>
Gesendet: Tuesday, July 18, 2023 4:38:41 PM
An: openrewrite/rewrite-migrate-java ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [openrewrite/rewrite-migrate-java] Calling "maybeRemoveImport(...)" does not remove import (Issue #262)


What version of OpenRewrite are you using?

2.0.7

How are you running OpenRewrite?

Unit Test

What is the smallest, simplest way to reproduce the problem?

Clone the project https://github.com/michael-schnell/openrewrite-issue/ and run the unit tests.

What did you expect to see?

There should be no test failure.

What did you see instead?

The Joda import is still there and makes the unit tests fail:
import org.joda.time.format.DateTimeFormatterBuilder;

**Comment by timtebeek** [comment]
I've created a fix for your tests and reported that here as a pull request:
https://github.com/michael-schnell/openrewrite-issue/pull/1
Hope that helps!
