### ISSUE TITLE
Recipe JakartaEE10 replaces wrongly javax.sql.DataSource into jakarta.sql.DataSource

### ISSUE THREAD

**Issue by marcwhitemore** [openrewrite/rewrite-migrate-java#439]
## How are you running OpenRewrite?
mvn -U org.openrewrite.maven:rewrite-maven-plugin:5.26.0:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-migrate-java:2.11.0 -Drewrite.activeRecipes=org.openrewrite.java.migrate.jakarta.JakartaEE10

Maven version used: 3.9.2

## What did you expect to see?
No changes to java.sql.DataSources references

## What did you see instead?
java.sql.DataSource is replaced by jakarta.sql.DataSource in web.xml deployment descriptor.

**Comment by timtebeek** [comment]
Thanks for the report @marcwhitemore ; This will be caused by the fairly course find an replace done on web.xml files
https://github.com/openrewrite/rewrite-migrate-java/blob/bc8e2f78861e714f5c677399ae69dd1f10c50bec/src/main/resources/META-INF/rewrite/jakarta-faces-4.yml#L217-L220

We'll either want to tweak that replacement, or do a subsequent replacement that changes the nonsensical `jakarta.sql` back into `java.sql`. Should be fairly straightforward I suppose. Would you want to try your hand at updating or adding that replacement?

**Comment by melloware** [comment]
I can fix this one.

**Comment by timtebeek** [comment]
Welcome back and thanks a lot!
