### ISSUE TITLE
Recipe JakartaEE10 does not proceed EJB deployment descriptor

### ISSUE THREAD

**Issue by marcwhitemore** [openrewrite/rewrite-migrate-java#440]
## How are you running OpenRewrite?
mvn -U org.openrewrite.maven:rewrite-maven-plugin:5.26.0:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-migrate-java:2.11.0 -Drewrite.activeRecipes=org.openrewrite.java.migrate.jakarta.JakartaEE10

Maven version used: 3.9.2

## What did you expect to see?
References to javax.* typed resources in ejb-jar.xml are replaced by jakarta.* references.
For example: <res-type>javax.jms.QueueConnectionFactory</res-type> should be replaced by <res-type>jakarta.jms.QueueConnectionFactory</res-type>
Note: the same kind of references are replaced correctly when they are defined in a Web deployment descriptor (web.xml). 

## What did you see instead?
No changes are made.

**Comment by timtebeek** [comment]
Thanks for the report! The cause here will be the same as this other case https://github.com/openrewrite/rewrite-migrate-java/issues/439#issuecomment-2103374472 : an over eager replacement pattern

https://github.com/openrewrite/rewrite-migrate-java/blob/bc8e2f78861e714f5c677399ae69dd1f10c50bec/src/main/resources/META-INF/rewrite/jakarta-faces-4.yml#L217-L220

We could fix both of these issues with a singe change I suppose.

**Comment by melloware** [comment]
I can fix this one.

**Comment by timtebeek** [comment]
Welcome back and thanks a lot!
