### ISSUE TITLE
No changes when running migration with gradle

### ISSUE THREAD

**Issue by unstko** [openrewrite/rewrite-migrate-java#87]
I have a project build with gradle. I set up the gradle build file by the description from https://docs.openrewrite.org/tutorials/migrate-from-java-8-to-java-11:

```
plugins {
    id("org.openrewrite.rewrite") version("5.19.2")
}

rewrite {
    activeRecipe("org.openrewrite.java.migrate.Java8toJava11")
}

repositories {
    mavenCentral()
}

dependencies {
    rewrite("org.openrewrite.recipe:rewrite-migrate-java:1.4.3")
}
```

Then I run `./gradlew rewriteRun` using the gradle wrapper from the project (version 7.4.2).
Then I get this output:

```
> Task :rewriteRun
Validating active recipes
Parsing sources from project foo
All sources parsed, running active recipes: org.openrewrite.java.migrate.Java8toJava11
```

And nothing changed! All files remain the same. I know there must be a migration of the XML binding framework from javax.xml.bind to jakarta.xml.bind for this project.

What might be the problem here?

**Comment by pway99** [comment]
Hi @unstko,  Looking at this again since I did not fully understand your original request.

There is indeed a bug, the recipe should be changing `javax.xml.bind` types to their `jakarta.xml.bind` equivalent.

https://github.com/openrewrite/rewrite-migrate-java/blob/feb2d1e1730444ced1391d5eaa42fb171222cd44/src/main/resources/META-INF/rewrite/javax-to-jakarta.yml#L35

https://github.com/openrewrite/rewrite-migrate-java/blob/feb2d1e1730444ced1391d5eaa42fb171222cd44/src/main/resources/META-INF/rewrite/javax-to-jakarta.yml#L370-L373

At this time I am thinking that a change to wild card matching is related to this error and will investigate.

**Comment by pway99** [comment]
@unstko, after more investigation I have learned that the 8 to 11 migration will add the runtime implementation of jaxb, jax-ws and inject dependencies so, you can migrate to java 11 without ever adopting the new jakarta namespace.   It's a bit confusing since it includes some jakarta artifacts that still have the javax namespaces. 

For migrating deprecated `javax` packages to `jakarta` check out the [org.openrewrite.java.migrate.JavaxMigrationToJakarta](https://github.com/openrewrite/rewrite-migrate-java/blob/feb2d1e1730444ced1391d5eaa42fb171222cd44/src/main/resources/META-INF/rewrite/javax-to-jakarta.yml#L18) recipe.

here are a few helpful notes on this subject
https://github.com/openrewrite/rewrite-migrate-java#java-architecture-for-xml-binding-jaxb
https://github.com/openrewrite/rewrite-migrate-java#java-api-for-xml-web-services-jax-ws

**Comment by pway99** [comment]
Hi @unstko, I am going to go ahead and close this issue, if it's still a problem please don't hesitate re-open.

**Comment by unstko** [comment]
@pway99 Thank you for your responses and sorry for the delay.

Now it works for me. I added the recipe "org.openrewrite.java.migrate.JavaxMigrationToJakarta" and then the migration changed my files.

**Comment by pway99** [comment]
Thanks @unstko glad to here its working for you
