### ISSUE TITLE
Apache Camel migrations

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-migrate-java#97]
Is there any interest to add recipes for Apache Camel? 

https://camel.apache.org/manual/camel-3-migration-guide.html

Apache Camel + Spring is a common pattern that I've seen that we could integrate with the Spring module 

https://camel.apache.org/camel-spring-boot/3.16.x/spring-boot.html

**Comment by tkvangorder** [comment]
This seems like a very good idea, if there is someone with expertise with Camel migrations, the OpenRewrite community would love to work with them to build out the recipe catalog.

**Comment by timtebeek** [comment]
Given the breadth of Apache Camel, I'd lean towards pushing this request towards the Apache Camel project itself; We have had quite some projects take up migration recipes themselves recently (Quarkus, Apache Wicket, AxonFramework, Cucumber-JVM), and I feel that might be a better fit rather than trying to support all of that here.

**Comment by yeikel** [comment]
> Given the breadth of Apache Camel, I'd lean towards pushing this request towards the Apache Camel project itself; We have had quite some projects take up migration recipes themselves recently (Quarkus, Apache Wicket, AxonFramework, Cucumber-JVM), and I feel that might be a better fit rather than trying to support all of that here.
> 
> Would you agree what we close this issue here @yeikel ?

That's fair. I am okay to close it
